# CMake generated Testfile for 
# Source directory: /home/ignacio/ibex_revmono/tests
# Build directory: /home/ignacio/ibex_revmono/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TestAgenda "TestAgenda")
set_tests_properties(TestAgenda PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestArith "TestArith")
set_tests_properties(TestArith PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestBitSet "TestBitSet")
set_tests_properties(TestBitSet PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestBoolInterval "TestBoolInterval")
set_tests_properties(TestBoolInterval PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestBxpSystemCache "TestBxpSystemCache")
set_tests_properties(TestBxpSystemCache PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestCell "TestCell")
set_tests_properties(TestCell PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestCov "TestCov")
set_tests_properties(TestCov PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestCross "TestCross")
set_tests_properties(TestCross PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestCtcExist "TestCtcExist")
set_tests_properties(TestCtcExist PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestCtcForAll "TestCtcForAll")
set_tests_properties(TestCtcForAll PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestCtcFwdBwd "TestCtcFwdBwd")
set_tests_properties(TestCtcFwdBwd PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestCtcHC4 "TestCtcHC4")
set_tests_properties(TestCtcHC4 PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestCtcInteger "TestCtcInteger")
set_tests_properties(TestCtcInteger PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestCtcNotIn "TestCtcNotIn")
set_tests_properties(TestCtcNotIn PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestDim "TestDim")
set_tests_properties(TestDim PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestDomain "TestDomain")
set_tests_properties(TestDomain PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestDoubleHeap "TestDoubleHeap")
set_tests_properties(TestDoubleHeap PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestDoubleIndex "TestDoubleIndex")
set_tests_properties(TestDoubleIndex PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestEval "TestEval")
set_tests_properties(TestEval PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestExpr2DAG "TestExpr2DAG")
set_tests_properties(TestExpr2DAG PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestExpr2Minibex "TestExpr2Minibex")
set_tests_properties(TestExpr2Minibex PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestExprCmp "TestExprCmp")
set_tests_properties(TestExprCmp PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestExprCopy "TestExprCopy")
set_tests_properties(TestExprCopy PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestExpr "TestExpr")
set_tests_properties(TestExpr PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestExprDiff "TestExprDiff")
set_tests_properties(TestExprDiff PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestExprLinearity "TestExprLinearity")
set_tests_properties(TestExprLinearity PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestExprMonomial "TestExprMonomial")
set_tests_properties(TestExprMonomial PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestExprPolynomial "TestExprPolynomial")
set_tests_properties(TestExprPolynomial PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestExprSimplify "TestExprSimplify")
set_tests_properties(TestExprSimplify PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestExprSimplify2 "TestExprSimplify2")
set_tests_properties(TestExprSimplify2 PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestFncKuhnTucker "TestFncKuhnTucker")
set_tests_properties(TestFncKuhnTucker PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestKuhnTuckerSystem "TestKuhnTuckerSystem")
set_tests_properties(TestKuhnTuckerSystem PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestFunction "TestFunction")
set_tests_properties(TestFunction PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestGradient "TestGradient")
set_tests_properties(TestGradient PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestHC4Revise "TestHC4Revise")
set_tests_properties(TestHC4Revise PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestInHC4Revise "TestInHC4Revise")
set_tests_properties(TestInHC4Revise PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestInnerArith "TestInnerArith")
set_tests_properties(TestInnerArith PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestInterval "TestInterval")
set_tests_properties(TestInterval PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestIntervalMatrix "TestIntervalMatrix")
set_tests_properties(TestIntervalMatrix PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestIntervalVector "TestIntervalVector")
set_tests_properties(TestIntervalVector PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestKernel "TestKernel")
set_tests_properties(TestKernel PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestLinear "TestLinear")
set_tests_properties(TestLinear PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestLPSolver "TestLPSolver")
set_tests_properties(TestLPSolver PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestNewton "TestNewton")
set_tests_properties(TestNewton PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestNumConstraint "TestNumConstraint")
set_tests_properties(TestNumConstraint PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestParser "TestParser")
set_tests_properties(TestParser PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestPdcHansenFeasibility "TestPdcHansenFeasibility")
set_tests_properties(TestPdcHansenFeasibility PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestRoundRobin "TestRoundRobin")
set_tests_properties(TestRoundRobin PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestSeparator "TestSeparator")
set_tests_properties(TestSeparator PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestSet "TestSet")
set_tests_properties(TestSet PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestSinc "TestSinc")
set_tests_properties(TestSinc PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestSolver "TestSolver")
set_tests_properties(TestSolver PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestString "TestString")
set_tests_properties(TestString PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestSymbolMap "TestSymbolMap")
set_tests_properties(TestSymbolMap PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestSystem "TestSystem")
set_tests_properties(TestSystem PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestTimer "TestTimer")
set_tests_properties(TestTimer PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestTrace "TestTrace")
set_tests_properties(TestTrace PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestVarSet "TestVarSet")
set_tests_properties(TestVarSet PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestCellHeap "TestCellHeap")
set_tests_properties(TestCellHeap PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestCtcPolytopeHull "TestCtcPolytopeHull")
set_tests_properties(TestCtcPolytopeHull PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestOptimizer "TestOptimizer")
set_tests_properties(TestOptimizer PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
add_test(TestUnconstrainedLocalSearch "TestUnconstrainedLocalSearch")
set_tests_properties(TestUnconstrainedLocalSearch PROPERTIES  _BACKTRACE_TRIPLES "/home/ignacio/ibex_revmono/tests/CMakeLists.txt;34;add_test;/home/ignacio/ibex_revmono/tests/CMakeLists.txt;0;")
