/* This file is automatically generated */

#ifndef __IBEX_SETTING_H__
#define __IBEX_SETTING_H__

#define _IBEX_RELEASE_ "2.8.9.1"
#define _IBEX_INTERVAL_LIB_ "gaol"
#define _IBEX_LP_LIB_ "none"

#endif /* __IBEX_SETTING_H__ */
